### ISSUE TITLE
Is it possible to prevent fields from being used as features but keep them as output fields?

### ISSUE THREAD

**Issue by alexnikitchuk** [salesforce/TransmogrifAI#209]
**Problem**
More question than problem:
In my case some fields contain auxiliary information that I need to have in the output but at the same time these fields can have high correlation with target label.
Is it possible to prevent fields from being used as features but keep them as output fields?

**Solution**
Unknown

**Alternatives**
Unknown

**Additional context**
N/A

**Comment by tovbinm** [comment]
@alexnikitchuk when you say "have in the output" do you mean as an output of the `model.score` execution?

**Comment by tovbinm** [comment]
hmm, we dont support it in our workflows, but you can do something like in the snipped below:
```scala

val includedFeature1: FeatureLike[_ <: FeatureType] = ...
val includedFeature2: FeatureLike[_ <: FeatureType] = ...
val excluded: FeatureLike[_ <: FeatureType] = ... // say we want to exclude this feature from the modeling

// generate data with only the features you need

val model = new OpWorkflow().setReader(trainReader).setResultFeatures(includedFeature1, includedFeature2).train()
val scores: DataFrame = model.score()

// load the data again with the features that were excluded and join with scores
val excludedData: DataFrame = reader.generateDataFrame(Array(excludedFeature1))
val joinedData: DataFrame = scores.join(excludedData, column("key"))
```

**Comment by snabar** [comment]
Actually here is how you can do it:

val f1: FeatureLike ... = ....
val label: FeatureLike ... = ...
val f2: FeatureLike ... = ...

val pred = BinaryClassificationModelSelector().setInput(label, f1).getOutput()

val fittedWorkflow = new OPWorkflow().setReader(reader).setResultFeatures(f2, pred).train()

val df = fittedWorkflow.score()

df should be a dataframe with f2 and pred as columns where pred used only f1 as the predictor.

**Comment by snabar** [comment]
In general, this diagram may help you understand what happens when you call “train” on a workflow:

https://github.com/salesforce/TransmogrifAI/blob/master/resources/workflows.png

Essentially the underlying DAG needed to materialize ResultFeatures gets prepped, i.e., any estimators (in the above case, the binary classification model selector) get fitted on the data.

When you then call score on the resulting workflowModel, data is run through the prepped DAG and *all* the ResultFeatures get materialized, whether or not they were a part of an estimator in the DAG.

https://github.com/salesforce/TransmogrifAI/blob/master/resources/materializingdata.png
