### ISSUE TITLE
Labels may not be dropped in MultiClassClassification

### ISSUE THREAD

**Issue by gerashegalov** [salesforce/TransmogrifAI#245]
**Describe the bug**
Dropping the long tail of low cardinality labels is currently performed DataCutter.prepare. There are multiple call paths and we see it skipped in production. This results in performance degradation or even pipeline failures violating various constraints in MLlib such as 
- 100 label limit in Classifier
- "dense matrix too large"

**To Reproduce**
internal pipeline, failing to reproduce in unit tests yet

**Expected behavior**
an easier way to reason that DataCutter is not bypassed.

**Logs or screenshots**

**Additional context**

**Comment by tovbinm** [comment]
@gerashegalov can we please also consider using HLL instead of Map when computing cardinality? @mweilsalesforce already started a related implementation on pivot with HLL #241 which you might be interested to look at.

**Comment by gerashegalov** [comment]
I suggested approximate accounts on various occasions. Spark implements them on DF https://databricks.com/blog/2016/05/19/approximate-algorithms-in-apache-spark-hyperloglog-and-quantiles.html

**Comment by michaelweilsalesforce** [comment]
@tovbinm @gerashegalov Indeed I implemented a HLL Aggregator for my vectorizer.

Trying Spark's sql function `approx_count_distinct` instead.

Issue I'm having is my input is a `Dataset[Seq[T#Value]]`. If I want to count each element I'll need to "explode" the Data. After doing that, `approx_count_distinct` can't be used because we are using kryo Encoder.

This is for the Vectorizer. For the MapVectorizer, I'll have to "explode" the `Dataset[Seq[Map[String, T]]]` which does not seem to be a good strategy.

**Comment by michaelweilsalesforce** [comment]
For the issue of MultiClass labels, `approx_count_distinct` can be used though.
