### ISSUE TITLE
Why does xgboost classifier sometimes give probability which >1 or <0?  

### ISSUE THREAD

**Issue by liuxiaodong008008** [salesforce/TransmogrifAI#398]

**Comment by tovbinm** [comment]
I would like to see that example. Seems like a bug.

**Comment by liuxiaodong008008** [comment]
It seems the default param grid for xgboost in BinaryClassificationSelector does not contains `objective` parameters.

**Comment by tovbinm** [comment]
Oh. We might have missed it. Did it resolve your issues? Would you care to open a PR with a fix + test?

**Comment by shenzgang** [comment]
hi!how do you add bayesian parameters? Is there any example code?

**Comment by tovbinm** [comment]
@shenzgang you can pass xgboost argument with the [model selector](https://docs.transmogrif.ai/en/stable/automl-capabilities/index.html?highlight=modelselector#modelselectors) or directly to the xgboost estimator.
Using model selector:
```scala
val xgb = new OpXGBoostClassifier()
val xgbParams = new ParamGridBuilder()
        .addGrid(xgb.numRound, 3)
        .addGrid(xgb.maxDepth, 10)
        .build()
val modelSelector = BinaryClassificationModelSelector
       .withCrossValidation(modelsAndParameters = Seq(xgb -> xgbParams))
val prediction = modelSelector.setInput(label, features).getOutput
```
Directly:
```scala
val prediction = new OpXGBoostClassifier().setNumRound(3).setMaxDepth(10).setInput(label, features).getOutput
```
Finally add it to your workflow:
```scala
val model = new OpWorkflow().setInputReader(reader).setResultFeatures(prediction).train()
```

**Comment by shenzgang** [comment]
@tovbinm I want to use not only grid search parameters but also bayesian algorithms to call them. I want to try to add bayesian parameters to modelsAndParams. There is a class called ParamGridBuilder
Is there no class like ParamGridBuilder? And how should I implement grid search and bayesian call?

**Comment by leahmcguire** [comment]
So I current implementation for hyper parameter selection does the search in parallel across all combinations of hyper parameters fed in. Not really compatible with bayesian hyper parameter selection. We have an implementation of random search rather than grid search so you can do random parameter search. https://github.com/salesforce/TransmogrifAI/blob/master/core/src/test/scala/com/salesforce/op/stages/impl/selector/RandomParamBuilderTest.scala
If you want to use Baysean hyper parameter selection you would need to do the parameter optimization outside of TM and feed the parameters into your workflow.
