### ISSUE TITLE
How can I get the trainset, validationset and holdoutset that modelselectors use internally？

### ISSUE THREAD

**Issue by liuxiaodong008008** [salesforce/TransmogrifAI#400]

**Comment by tovbinm** [comment]
I don't believe we expose those datasets. But you can recreate them by applying `split` and `validationPrepare` methods on `splitter`/`datacutter` instances with training datasets.

https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala

**Comment by liuxiaodong008008** [comment]
`split` returns `(dataTrain, dataTest)`. `validationPrepare ` does data balancing or dropping based on the labels before splitting `dataTrain` into trainset and validationset.  So, how to split `dataTrain` into trainset and validationset?

**Comment by leahmcguire** [comment]
if you set the seed on the splitter the dataTest returned will be the holdout dataset and the dataTrain will be the training and validation data. Separating out the training and validation data for examination is not really possible since it will depend on the validation method used (eg cross validation or training split) and this is only done internal to the model selector call.
