### ISSUE TITLE
Remove or document Direct Output Committers limitations

### ISSUE THREAD

**Issue by gerashegalov** [salesforce/TransmogrifAI#54]
**Describe the bug**
Direct output committer and vanilla committers are susceptible to list inconsistency on s3. It only works with layers on top of s3 such as [S3Guard](https://hadoop.apache.org/docs/current3/hadoop-aws/tools/hadoop-aws/committers.html) or EMRFS as long as one relies on _SUCCESS files. 

**To Reproduce**
Run on pure s3 :)

**Expected behavior**
 Use the default committer. Just refer users to options out there and how to configure them

**Logs or screenshots**
N/A

**Additional context**
N/A

**Comment by ajayborra** [comment]
Hi @gerashegalov, Was able to reproduce this issues and following are the observations.

- When we use paths with `(s3|s3n)://<object key>` format, code crashes with `No FileSystem for scheme: (s3|s3n)`.
|- Seems like it is possible to detect this prefixes early on and raise an error indicating the fact and recommend using `s3a` [here](https://github.com/salesforce/TransmogrifAI/blob/master/utils/src/main/scala/com/salesforce/op/utils/io/avro/AvroInOut.scala#L90) and document this fact.
- Default implementation for `s3` is configured as `s3a` [`org.apache.hadoop.fs.s3a.S3AFileSystem`](https://github.com/salesforce/TransmogrifAI/blob/master/gradle/spark.gradle#L62)
|- Seems like we can still use `org.apache.hadoop.fs.s3native.NativeS3FileSystem` even though its in [maintanace mode](https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html#S3N). So we can document this fact and how to configure it. (An alternative could be, we can provide a cli level `--s3-scheme` flag to choose `s3a` vs `s3n` scheme and set these properties programatically -- Let me know your thoughs on this).

Also, Can you please expand a bit more on the **Expected behavior** section. Are you refering to chainging the behaviour of [DirectOutputCommitter](https://github.com/salesforce/TransmogrifAI/blob/master/utils/src/main/scala/com/salesforce/op/utils/io/DirectOutputCommitter.scala) class in some way ?

**Comment by gerashegalov** [comment]
Hi @ajayborra, 

thank you for checking out the issue. 

just for the reference: s3n is deprecated in Hadoop 2.x and removed in Hadoop 3.x . I would like to point out that the issue is related to this but not about FileSystem URI's. And yes S3 conf is missing in the default Hadoop libraries outside EMR.

It's rather about hadoop output committers. I propose dropping DOC classes from these project. We should definitely not hardcode them like in https://github.com/salesforce/TransmogrifAI/blob/f37997578ae8fa36528e8e697da8747f30feb97f/utils/src/main/scala/com/salesforce/op/utils/io/avro/AvroInOut.scala#L159 because it introduces inconsistency windows on HDFS.

The expected behavior I think should be the default output committer as in Hadoop 3, FileOutputCommitter v2: https://docs.databricks.com/spark/latest/faq/append-slow-with-spark-2.0.0.html

**Comment by ajayborra** [comment]
@gerashegalov Thanks for clarifying on this. +1 on leaving it to the users to choose the committer class. Raised a PR for this https://github.com/salesforce/TransmogrifAI/pull/86. Please review it when you get a chance.
