### ISSUE TITLE
Quick Start Examples (Titanic) Does not Build with master

### ISSUE THREAD

**Issue by himsmittal** [salesforce/TransmogrifAI#74]
**Describe the bug**
When using titanic dataset (Bootstrap Your First Project page) ,
 ./gradlew compileTestScala installDist 
command is trying to pull *core-3.50-snapshot jar, which is not available. This causes the build to fail.

**To Reproduce**
Run the steps mentioned in Bootstrap Your First Project on master branch. It would fail for  ./gradlew compileTestScala installDist 
It works for 0.3.4 branch only.
**Expected behavior**
For developers : it should work on master 
Possible solution : Use shadowJar to generate core jar which will have the desired dependencies and then use the local jars for building by adding flatDir path in the gradle template.

**Logs or screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Additional context**

**Comment by tovbinm** [comment]
You can publish local `0.3.5-SNAPSHOT`, then the cli generated project build would work. Otherwise a developer cal manually update the TransmogrifAI version number of the generated project. So I dont this is real issue.

I did update the documentation to reflect the point that one should checkout the relaese branch first - https://github.com/salesforce/TransmogrifAI/wiki/Bootstrap-Your-First-Project#quick-start

**Comment by tovbinm** [comment]
In general, it perhaps makes sense to release a shadow cli jar, so that one would not even need to clone the repo to bootstrap a new project.

**Comment by himsmittal** [comment]
Thanks for the response. Closing the issue.
